### ISSUE TITLE
One Signal Issues With Rock RMS - Person Alias ID Error

### ISSUE THREAD

**Issue by adamhann** [lcbc-digital/ephesus#42]
**Describe the bug**
When the One Signal transport is Active in Rock, it causes issues with sending Emails/SMS when using the "User Preference" setting. It can't always send all of the messages and we get this error. 

`"Int32 Rock.Model.CommunicationRecipient.get_PersonAliasldO'`

When this happens it locks up the communication in a pending state and Rock starts through exceptions every 15 minutes. 

**To Reproduce**
1. Go to new communication and start to create a new message. 
2. Select User Preference when selecting how to send the message.
3. Create the Email and SMS version of the communication. 
4. Try to send the communication and the error will happen. 

**Expected behavior**
The expected behavior is for the Email or SMS to send without any issues. 

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/23084345/144257567-6a9e4d45-eb59-4a65-a668-9052140c1297.png)

**Additional context**
We first asked Triumph to look into this issue to make sure it wasn't something setup with our Rock instance. Here's their response. 

> All of the failed communications have a 'Pending' SMS in the delivery status which led us to look into the communication transports. Through testing we were able to determine that communications is having an issue with OneSignal. We can duplicate the issue by sending an SMS message while OneSignal is active, this throws an error (see second screenshot) but when the same SMS message is sent with OneSignal inactivated it completes successfully (see first screenshot). It may be possible that OneSignal is having a complication with the recent update to v12.6?

**Comment by conrad-vanl** [comment]
@richarddubay would you be able to look at this and let me know if it makes sense to you?

@adamhann just to confirm, you're not trying to send SMS/Email through OneSignal are you? I believe our OneSignal transport only works for push notifications right now

**Comment by adamhann** [comment]
@conrad-vanl Correct. We only have OneSignal setup to do Push Notifications. We are using Twilio for SMS and Mailgun for Email. You can see the attached screenshots for our setup. 
<img width="1292" alt="Screen Shot 2021-12-01 at 2 48 15 PM" src="https://user-images.githubusercontent.com/23084345/144303681-19e144e1-e5e6-49a0-b058-a772fbe8ed52.png">
<img width="1185" alt="Screen Shot 2021-12-01 at 2 47 29 PM" src="https://user-images.githubusercontent.com/23084345/144303703-4a502ee5-3abf-4ba2-ae52-2f830a93cefe.png">
<img width="1185" alt="Screen Shot 2021-12-01 at 2 47 36 PM" src="https://user-images.githubusercontent.com/23084345/144303704-b1cbf890-8812-4238-a255-a672bab7c30b.png">
<img width="1195" alt="Screen Shot 2021-12-01 at 2 47 46 PM" src="https://user-images.githubusercontent.com/23084345/144303707-9a228eba-5055-405d-8bc2-1eb57e8d13ac.png">

**Comment by conrad-vanl** [comment]
@richarddubay is going to be looking into this.

@adamhann in the meantime if you un-checked "Active" on the OneSignal transport in rock, I assume SMS/Emails send successfully?

This _was_ working when you first installed the plugin right? Was there a Rock update since then do you remember?

**Comment by conrad-vanl** [comment]
Ok good to know. We'll try to fix this quickly, but with general troubleshooting and timeline on deploying a Rock Plugin update there will be a little bit of lead time at minimum. 

Are you trying to send pushes to certain segments, or all app users? I ask because I can get you all set up in One Signal directly if you want to send something more church-wide.

**Comment by richarddubay** [comment]
I seem to remember NewSpring having some issues with communications not working correctly when the OneSignal plugin was active too. I thought it was because they were pulling pre-alpha version 13 and it was something in there but maybe Spark released the same kind of thing early in 12.6. I'll take a look at it and see what I can find. 👍🏼

**Comment by notGerryMiller** [comment]
This appears to have been caused by our build process pulling in an old DLL.  We updated to the latest and greatest and will keep an eye on it.
