### ISSUE TITLE
Users randomly logged out from the app

### ISSUE THREAD

**Issue by notGerryMiller** [lcbc-digital/ephesus#43]
**Describe the bug**
Users seem to be randomly getting logged out from the app. They appear to be logged in but when they go to click on something that takes them to a rock form they are not authenticated. I.E. Check-in or Prayer Requests shows them as unauthenticated or doesn't prepopulate and fields.  This had been happening for a few weeks/months now. At first, we thought it was related to our issues in August and getting everyone logged back in. It appears now that isn't the case. You could have a fresh install and fresh user authentication and be logged out within a few days.

This weekend we had 5555 app check-in as of 12/06/2021.  1293 of them had to use the form to authenticate to the workflow since they were not in an authenticated in the webview.

**To Reproduce**
1. Open App
2. Click on Checkin
3. If you have a form where you have to enter your name to are not logged in. If you have the normal check-in form you are logged in.

**Expected behavior**
User should be passed into rock with an authenticated sessions.

**Screenshots**
Working:
![image](https://user-images.githubusercontent.com/53865308/144864034-57e3c171-e8fe-4f23-a0a1-506b9d4b1d78.png)
![image](https://user-images.githubusercontent.com/53865308/144864304-980d1cfd-ed17-4125-a7bb-183e5054437d.png)

Broken:
URL that is missing the person token: https://app.lcbcchurch.com/AppCheckin?rckipid=
![image](https://user-images.githubusercontent.com/53865308/144863805-e10bd83a-411b-4c8d-92bf-2b3e99a5baf0.png)
![image](https://user-images.githubusercontent.com/53865308/144864331-45237431-bf0e-41fa-86c4-ef97fb9df135.png)

**Additional context**

**Comment by conrad-vanl** [comment]
This is fixed in https://github.com/lcbc-digital/ephesus/commit/2496ffdd9a86aa084c4512e9534333e1cd02b548
