### ISSUE TITLE
Unable to authenicate user through the Rock Web Farm

### ISSUE THREAD

**Issue by notGerryMiller** [lcbc-digital/ephesus#44]
**Describe the bug**
When the Apollos API is pointed at the web farm it is not able to authenticate the user. When trying to use the GetCurrentPerson API endpoint with a cookie generated via the API it generates a 404. 

**To Reproduce**
1. Generate a cookie via the API endpoint
`POST https://rock-gateway.lcbcchurch.com/api/Auth/Login
{
  Username: "...",
  Password: "...",
  Persisted: true
}`
2. Use the cookie with the GetCurrentPerson API endpoint via the gateway and you will get a 404.
`curl -X GET --header 'Accept: application/json' 'https://rock-gateway.lcbcchurch.com/api/People/GetCurrentPerson' --cookie ".ROCK_SESSION_AFFINITYCORS=XXXXXXXX; Path=/; SameSite=None; Secure, .ROCK_SESSION_AFFINITY=XXXXXX; Path=/, .ROCK=XXXXX" -v`

It works properly if you hit the web interface to generate the cookie and then use that in API request.
`This cURL is succeeding, and use a Cookie that was generated by logging into Rock on the web:
curl -X GET --header 'Accept: application/json' 'https://rock-gateway.lcbcchurch.com/api/People/GetCurrentPerson' --cookie 'Cookie: last_site=1; .ROCK=XXXXXXXXXXXXXXXX; ASP.NET_SessionId=eXXXXXXXrr4ajsa; .ROCK_SESSION_AFFINITY=XXXXXXX; .ROCK_SESSION_AFFINITYCORS=XXXXXXX; _fbp=fb.1.1636384000307.1360957145; _ga=GA1.2.14371938.1636384000' -v`

**Expected behavior**
The current person would be returned via the API

* **Rock Version:** 12.6.1
* **Client Culture Setting:** en-US

**Comment by notGerryMiller** [comment]
I was just able to generate a cookie the API through the webfarm. I ran the following curl from the command line.

```
url -X POST -H "Content-Type: application/json" \
    -d '{ Username: "XXXXX", Password: "XXXXX", Persisted: true }' \
    https://rock.lcbcchurch.com/api/Auth/Login -v
```
I get 
```
The following is returned:
*   Trying 20.109.112.172:443...
* Connected to rock.lcbcchurch.com (20.109.112.172) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.lcbcchurch.com
*  start date: Oct 27 07:04:59 2021 GMT
*  expire date: Oct 26 14:31:40 2022 GMT
*  subjectAltName: host "rock.lcbcchurch.com" matched cert's "*.lcbcchurch.com"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
> POST /api/Auth/Login HTTP/1.1
> Host: rock.lcbcchurch.com
> User-Agent: curl/7.77.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 69
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Date: Wed, 15 Dec 2021 20:25:19 GMT
< Connection: keep-alive
< Set-Cookie: .ROCK_SESSION_AFFINITYCORS=XXXX; Path=/; SameSite=None; Secure
< Set-Cookie: .ROCK_SESSION_AFFINITY=XXXX Path=/
< Cache-Control: no-cache
< Pragma: no-cache
< Expires: -1
< Set-Cookie: XXXXX
< 
* Connection #0 to host rock.lcbcchurch.com left intact
```

I then took the cookie and dumped in into the next curl and it appears to be working.     

```
curl -X GET --header 'Accept: application/json' 'https://rock-gateway.lcbcchurch.com/api/People/GetCurrentPerson' --cookie ".ROCK=XXXXX" -v 
```
I get 
```
*   Trying 20.109.112.172:443...
* Connected to rock-gateway.lcbcchurch.com (20.109.112.172) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.lcbcchurch.com
*  start date: Oct 27 07:04:59 2021 GMT
*  expire date: Oct 26 14:31:40 2022 GMT
*  subjectAltName: host "rock-gateway.lcbcchurch.com" matched cert's "*.lcbcchurch.com"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
> GET /api/People/GetCurrentPerson HTTP/1.1
> Host: rock-gateway.lcbcchurch.com
> User-Agent: curl/7.77.0
> Cookie: .ROCK=5A5D297F58C1290479775534A02E2C5505606A0CF1D63D4C599A9D1EB27B7E07EAACB2AB91C83EC94EFF5E3F3103A20569642498BC208D15BD53371BBA3D2F0D0EBE077C1ECBF5004F92CE26208BD162577002923A7CBA10EF6D135B648DEF2D0F0C2D68; expires=Fri, 14-Jan-2022 20:24:16 GMT; path=/;SameSite=Lax;Secure; secure; HttpOnly
> Accept: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 15 Dec 2021 20:26:50 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 13293
< Connection: keep-alive
< Set-Cookie: .ROCK_SESSION_AFFINITYCORS=XXXXX; Path=/; SameSite=None; Secure
< Set-Cookie: .ROCK_SESSION_AFFINITY=XXXXX; Path=/
< Cache-Control: no-store
< 
{"ConnectionStatusValue":
```

**Comment by conrad-vanl** [comment]
@notGerryMiller (your username is so confusing) looking closely at your CURL logs above - it looks like the first curl you ran against `rock.lcbcchurch.com` and the second to `rock-gateway.lcbcchurch.com`. For posterity, can you confirm which one of those points to the webform, and confirm that this is working for you when you make both requests against the same host?

**Comment by notGerryMiller** [comment]
Both point to the web farm. That was sloppy of me. I just ran both curls as rock.lcbchurch.com and got the same results. I can post if you want, but they look just like the ones above.

```
gerrymiller@lcbc-pc-3klq05p ~ % nslookup rock-gateway.lcbcchurch.com
Server:		10.1.20.120
Address:	10.1.20.120#53

Non-authoritative answer:
Name:	rock-gateway.lcbcchurch.com
Address: 20.109.112.172

gerrymiller@lcbc-pc-3klq05p ~ % nslookup rock.lcbcchurch.com       
Server:		10.1.20.120
Address:	10.1.20.120#53

Non-authoritative answer:
Name:	rock.lcbcchurch.com
Address: 20.109.112.172
```

Also would you believe that someone already had gerrymiller on github!

**Comment by conrad-vanl** [comment]
@notGerryMiller if they both point to the web farm...then that confuses the heck out of me! We already have the app setup to direct traffic through rock.lcbcchurch.com:

![Screen Shot 2021-12-15 at 3 52 49 PM](https://user-images.githubusercontent.com/103927/146270786-93acf39d-3c0f-4a84-bfeb-d004397ae66d.png)

So if that's the case...the app is already directing traffic through the web farm?

**Comment by notGerryMiller** [comment]
Yep, but I think we are directing authentication around it?

**Comment by conrad-vanl** [comment]
Ah - @notGerryMiller you're right: https://github.com/lcbc-digital/ephesus/blob/609dd8cdd62aefe2293eca4f34cc2e1119021075/apollos-church-api/config.yml#L27

**Comment by notGerryMiller** [comment]
If you guys are comfortable switching it back we can try it.

**Comment by conrad-vanl** [comment]
Going to try it locally first - I was thinking about that and tempted. But since it's coded on GitHub it takes longer to change and change back, easier to just try it locally. I'll report back 😀

**Comment by conrad-vanl** [comment]
This has been fixed in https://github.com/lcbc-digital/ephesus/commit/2496ffdd9a86aa084c4512e9534333e1cd02b548
